### ISSUE TITLE
Typo in README.md: the section in composer.json is "extra", not "extras".

### ISSUE THREAD

**Issue by giriroub** [arokettu/composer-license-manager#2]
In the README.md it says to configure the plugin in the "extras" section of the composer.json. To my knowledge there is no such section and it doesn't work when using "extras", it has to be "extra" (https://getcomposer.org/doc/04-schema.md#extra).

**Comment by arokettu** [comment]
And in docs too. Fixed

**Comment by arokettu** [comment]
Thanks
